### ISSUE TITLE
Add link to the book in the repository "about" section

### ISSUE THREAD

**Issue by dellagustin-sap** [InnerSourceCommons/managing-inner-source-projects#35]
The URL on the about section should point to one of this two:
* https://innersourcecommons.gitbook.io/managing-inner-source-projects/
* https://innersourcecommons.org/learn/books/managing-innersource-projects/

**Comment by rrrutledge** [comment]
This is a good point - thanks for registering this issue!  For stuff like this I feel like it’s almost the same amount of time to just add in the links in a pull request if you very wanted to.  Either way is fine, though - I can try to get to it as well.

**Comment by dellagustin-sap** [comment]
Hi @rrrutledge , by "about" section, I mean the repository metadata in GitHub:

<img width="322" alt="image" src="https://github.com/InnerSourceCommons/managing-inner-source-projects/assets/54676965/02077551-aa59-48ab-a1ea-5ed46776c073">

<img width="637" alt="image" src="https://github.com/InnerSourceCommons/managing-inner-source-projects/assets/54676965/672a4295-0ba2-4ccf-8053-3c44b90a425b">


As far as I know I cannot propose that kind of change with a PR (although repo metadata as code would be a nice feature for GitHub).

**Comment by rrrutledge** [comment]
Oh!  Makes sense.  My apologies - I just learned something!

**Comment by dellagustin-sap** [comment]
@rrrutledge thank you for adding the link!
