### ISSUE TITLE
Cover image for the book

### ISSUE THREAD

**Issue by dicortazar** [InnerSourceCommons/managing-inner-source-projects#6]
We still need to produce a cover for this book. Let's see what we can do :).

**Comment by jsmanrique** [comment]
There is a [book.json](https://github.com/dicortazar/managing-inner-source-projects/blob/master/book.json) file to do it. It's just a matter of exploring the options ;-)

**Comment by dicortazar** [comment]
That book.json didn't work and I had to leave just one author. In the Inner Source Patterns book a cover.jpg was produced. You can download that at https://www.gitbook.com/book/dicortazar/inner-source-patterns/details .

I'd say that we should expect something closer to that.

**Comment by spier** [comment]
We do have a cover image here now?
https://innersourcecommons.org/learn/books/managing-innersource-projects/

Would you like to add that cover image to the first page in the book, just like we did it here?
https://patterns.innersourcecommons.org/

**Comment by spier** [comment]
This issue here has been addressed for a while already.

**Comment by rrrutledge** [comment]
You made a great cover!
