### ISSUE TITLE
[bug] Sub-chapters are not generated correctly

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/managing-inner-source-projects#9]
There is a bug with the sub-chapters shown in the left-hand menu of the book.

e.g. when selecting the [Development Process](https://innersourcecommons.gitbook.io/managing-inner-source-projects/infrastructure/basic-infrastructure/development-process) sub chapter, no content is rendered.

See screenshot:

![sub-chapters-not-rendered](https://user-images.githubusercontent.com/163029/117263488-9bd65b80-ae52-11eb-931f-c3227533aa45.JPG)

**Comment by spier** [comment]
I have reached out to the gitbook Support team to ask how we can fix this. Likely some changes in [SUMMARY.md](https://github.com/InnerSourceCommons/managing-inner-source-projects/blob/master/SUMMARY.md) are required.

Let's see what they will say.

**Possible quick fix:**

We could fix this quickly by removing all sub-chapters from there. However that would mean that most deep links that the book used to have will disappear.

**Comment by spier** [comment]
Info I got from gitbook

> Having a target link in the SUMMARY.md file is not supported with GitBook New.
> 
> If it is important for that content to be exposed in the Table of Contents, it should be a page on its own. Possibly grouped under the higher level page it belong conceptually.
>

**Comment by spier** [comment]
@dicortazar what's your take on the above?

Would you like to keep the old table of contents structure in the left-hand menu?
To do so, we have to split up the files. One file for each menu item. e.g. `infrastructure/infrastructure.md` would have to be broken up into 6 different files, if I see this correctly.

```
* [Infrastructure](infrastructure/infrastructure.md)
  * [Basic Infrastructure](infrastructure/infrastructure.md#basic-infrastructure)
    * [Development Process](infrastructure/infrastructure.md#development-process-infrastructure)
    * [Communication Channels](infrastructure/infrastructure.md#communication-channels-infrastructure)
    * [Monitoring](infrastructure/infrastructure.md#monitoring-infrastructure)
  * [Comparing How Inner-Sourced Your Infra Is](infrastructure/infrastructure.md#comparing-how-inner-sourced-your-infrastructure-is)
  * [Authors and Reviewers](infrastructure/authors.md)
```

One additional benefit of this could be that when people start to contribute to this, we would end up with fewer merge conflicts most likely, as people would be working on separate files.

I am happy to do this splitting of files. Would allow me to learn more about the book.

**Comment by spier** [comment]
Just confirmed that this issue still exists in the [Infrastructure](https://innersourcecommons.gitbook.io/managing-inner-source-projects/infrastructure) chapter, as well as the Metrics/[Examples of Interest](https://innersourcecommons.gitbook.io/managing-inner-source-projects/introduction-1/metrics) sub-chapter.

I am suggesting to fix this like this:
1. [Infrastructure](https://innersourcecommons.gitbook.io/managing-inner-source-projects/infrastructure): split the content into 2 files - "Basic Infrastructure" and "Comparing how inner-sourced your infrastructure is"
2. [Examples of Interest](https://innersourcecommons.gitbook.io/managing-inner-source-projects/introduction-1/metrics): remove all the links below this from the menu, as this is already shown correctly in the menu on the right-hand side when the user clicks on the "Examples of Interest" sub-chapter.

I will create a PR for (2), and then another one for (1), once some open PRs related to that content are merged.

**Comment by rrrutledge** [comment]
Thank you for noticing this and fixing it!

**Comment by spier** [comment]
Confirmed that all links in the left-hand menu of the book are now working 🥇

**Comment by rrrutledge** [comment]
Wow 🤩
